Chapter 4
# **Linear Algebra**


#### What is Vector?

Simply put vector is an arrow in a space with a specific direction and length, often representing a piece of data. It has no concept of location, so always imagine it's tail starts at the origin of a Cartesian plane(0,0). A vector $v$ is denoted like this: $v⃗$

<p align="center"><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Vector_components.svg/1200px-Vector_components.svg.png" width=200></p>


To declare a vector, you can use NumPy's array() function then can pass a collection of numebers to it as below: 



In [ ]:
import numpy as np
v= np.array([3,2])
print(v)

[3 2]


A three dimensional vector:
$\vec{v} = \begin{bmatrix} x\\y\\z \end{bmatrix} = \begin{bmatrix} 4\\1\\2 \end{bmatrix} $

can be expressed in python like this:

In [ ]:
v=np.array([4,1,2])
print(v)

[4 1 2]


#### **Adding and Combining vectors**

If we have two vectors $\vec{v}$ and $\vec{w}$ how do we add these vectors?

$\vec{v}=\begin{bmatrix}3\\2\end{bmatrix}$

$\vec{w}=\begin{bmatrix}2\\-1\end{bmatrix}$

$\vec{v}+\vec{w}=\begin{bmatrix}3+2\\2+-1\end{bmatrix}=\begin{bmatrix}5\\1\end{bmatrix}$

In python:

In [ ]:
from numpy import array
v = array([3, 2])
w = array([2,-1])
v_plus_w = v + w
print(v_plus_w)

[5 1]


$\vec{v}+\vec{w} = \vec{w}+\vec{v}$

#### **Scaling Vectors**
Scaling is growing or shrinking a vector's length. You can grow/shrink a vector by multiplying or scaling it with a single value, known as $scalar$

$\vec{v}=\begin{bmatrix}3\\2\end{bmatrix}$

$2\vec{v}=\begin{bmatrix}3×2\\2×2\end{bmatrix} = \begin{bmatrix}6\\4\end{bmatrix}$

In [ ]:
from numpy import array
v=array([3,2])
scaled_v= 2*v
print(scaled_v)

[6 4]


Scaling a vector doesn't change it's direction. But when you multiply a vector by negative number it flips the direction of the vector as shown in the image.

<p align="center"><img src="https://www.storyofmathematics.com/wp-content/uploads/2020/10/Vector-multiplication-by-a-negative-scalar-300x258.png"></p>

Although it stays on the same line. This segues to a key concept called linear dependence.

#### **Span and Linear Dependence**

These two operaions adding and scaling vectors, bring about the idea that we can combine two vectors and scale them to create any resulting vector we want.
$\vec{v}+\vec{w}=\overrightarrow{v+w}$

Again, $\vec{v}$ and $\vec{w}$ are fixed in direction, except for flipping with negative scalars, but we can use scaling to freely create any vector composed of $\overrightarrow{v+w}$. This whole space of possible vectors is called $span$. When we have two vectors in two different directions they are $\textit{linearly independent}$ and have this unlimited span.

We are only limited in span when we have two vectors on the same line and in the same direction. No matter how we may scale or combine them the resulting vector is always going to be on that same line. This makes them $\textit{linearly dependent}.$

###**Linear Transformations**

#### **Basis Vectors**

Imagine we have two simple vectors $\hat{i}\,\text{and}\,\hat{j}$. These are known as basis vectors, which are used to describe transformations on other vectors. They typically have a length of 1 and point in perpendicular positive directions.
Think of the basis vectors as building blocks to build or transform any vector. Our basis vector is expressed in a 2 × 2 matrix, where the first column is $\hat{i}$ and the second is column is $\hat{j}$ :

$\hat{i}$ = $\begin{bmatrix}1\\0\end{bmatrix}$

$\hat{j}$ = $\begin{bmatrix}0\\1\end{bmatrix}$

$\text{basis}$ = $\begin{bmatrix}1\,\,\,\,\,\,0 \\0\,\,\,\,\,\,1\end{bmatrix}$

$\vec{v}=\hat{i}+\hat{j}$



#### **Matrix Vector Multiplication**

The formula to transform a vector $\vec{v}$ given basis vectors $\hat{i}$ and $\hat{j}$ packaged as a matrix is:

$\begin{bmatrix}x_{new}\\y_{new}\end{bmatrix} = \begin{bmatrix}a\,\,\,b\\c\,\,\,d \end{bmatrix}\begin{bmatrix}x\\y\end{bmatrix}=\begin{bmatrix}ax+by\\cx+dy\end{bmatrix}$

In [ ]:
from numpy import array 
basis = array([[3,0],
               [0,2]])
v=array([1,1])
new_v=basis.dot(v)
print(new_v)

[3 2]


In [ ]:
i_hat = array([2,0])
j_hat = array([0,3])
#convert rows into columns
basis = array([i_hat,j_hat]).transpose()
v = array([2,1])

new_v=basis.dot(v)
print(new_v)

[4 3]


#### **Matrix Multiplication**

Here is how we apply a rotation and then shear to any vector $\vec{v}$ with value $[x,y]$:

$\begin{bmatrix}1\,\,\,\,1\\0\,\,\,\,1\end{bmatrix}$$\begin{bmatrix}0\,\,\,\,-1\\1\,\,\,\,\,\,\,\,\,\,0\end{bmatrix}$$\begin{bmatrix}x\\y\end{bmatrix}$ - - - - - - - - - - - - -(1)

$\begin{bmatrix}a\,\,\,\,b\\c\,\,\,\,d\end{bmatrix}$$\begin{bmatrix}e\,\,\,\,f\\g\,\,\,\,h\end{bmatrix}$= $\begin{bmatrix}ae+bg\,\,\,\,\,\,af+bh\\ce+dg\,\,\,\,\,\,cf+dh\end{bmatrix}$ - - - - - - - - - -(2)


Applying (2) on (1) we get:

$\begin{bmatrix}1\,\,\,-1\\1\,\,\,\,\,\,\,\,\,0\end{bmatrix}$$\begin{bmatrix}x\\y\end{bmatrix}$


In [ ]:
from numpy import array
i_hat1 = array([0,1])
j_hat1=array([-1,0])
transform1=array([i_hat1, j_hat1]).transpose()
i_hat2 = array([1,0])
j_hat2 = array([1,1])
transform2=array([i_hat2, j_hat2]).transpose()

#combine transformations
combined = transform2 @ transform1 # @ is the shorthand for matmul()

#test
print(f"Combined Matrix:\n{combined}")

Combined Matrix:
[[ 1 -1]
 [ 1  0]]


##### **Using dot() vs matmul() vs @**
Usually you want to prefer matmul() and it's shorhand @ to combine matrices rather than the dot() operator in NumPy. The former generally has a preferable policy for higher dimensional matrices and how the elements are broadcasted.

In [ ]:
from numpy import matmul
v = array([1,2])
print(combined.dot(v))
print(combined @ v)
print(matmul(combined,v))

[-1  1]
[-1  1]
[-1  1]


Note that we could also have applied each transformation individually to vector $\vec{v}$

In [ ]:
rotated = transform1.dot(v)
sheered = transform2.dot(rotated)
print(sheered)

[-1  1]


Remember the order of transformation matters!
If we flip the order as below, see how the result gets changed:

In [ ]:
combined = transform1 @ transform2 # sheer and then rotate
print(combined.dot(v))

[-2  3]


In [ ]:
transform2 #sheer

array([[1, 1],
       [0, 1]])

In [ ]:
transform1 #rotation 

array([[ 0, -1],
       [ 1,  0]])

#### **Determinants**

Determinant are the factor by which a sampled area from vector space is expanded and Squished.

If $\hat{i},\hat{j}$ is scaled and becomes $2\hat{i},3\hat{j}$ the determinant is therefore $2×3=6$

Determinants describe how much a sampled area in a vector space changes in scale with linear transformations and this can provide helpful information about the transformation.

In [ ]:
from numpy.linalg import det
from numpy import array 
i_hat = array([3,0])
j_hat = array([0,2])
basis = array([i_hat,j_hat]).transpose()
determinant=det(basis)
print(determinant) 

6.0


Sample shears and rotations should not affect the determinant, as the area will not change. 

In [ ]:
from numpy.linalg import det
from numpy import array 
i_hat = array([1,0])
j_hat = array([1,1])
basis = array([i_hat,j_hat]).transpose()
determinant=det(basis)
print(determinant) 

1.0


But scaling however, will increase or decrease determinant

In [ ]:
from numpy.linalg import det
from numpy import array 
i_hat = array([-2,1])
j_hat = array([1,2])
basis = array([i_hat,j_hat]).transpose()
determinant=det(basis)
print(determinant) 

-5.000000000000001


The most critical piece of information that a determinant gives us is whether the transformation is linearly dependent. If you have a determinant of 0, that means all of the space has been squished into a lesser dimension.

In [ ]:
from numpy.linalg import det
from numpy import array 
i_hat = array([-2,1])
j_hat = array([3,-1.5])
basis = array([i_hat,j_hat]).transpose()
determinant=det(basis)
print(determinant) 

0.0


#### **Systems of Equations and Inverse Matrices**

Below are the operations for these equations:
\begin{equation}
4x + 2y + 4z = 44\\
5x + 3y + 7z = 56\\ 
9x + 3y + 6z = 72\\
\end{equation}

In [1]:
from sympy import *
A = Matrix([
      [4,2,4],
      [5,3,7],
      [9,3,6]
      ])

inverse = A.inv() #inverse matrix calculations
identity = inverse*A #identity matrix calculations 
print(f"Inverse:{inverse}")
print(f"Identity:{identity}")

Inverse:Matrix([[-1/2, 0, 1/3], [11/2, -2, -4/3], [-2, 1, 1/3]])
Identity:Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])


In [3]:
from numpy import array 
from numpy.linalg import inv 
A = array([[4,2,4],
      [5,3,7],
      [9,3,6]])
B= array([
          44,
          56,
          72
])
X = inv(A).dot(B)
print(X)

[ 2. 34. -8.]


In [4]:
from sympy import * 
A = Matrix([[4,2,4],
      [5,3,7],
      [9,3,6]])
B= Matrix([
          44,
          56,
          72
])
X = A.inv() * B 
print(X)

Matrix([[2], [34], [-8]])


#### **Eigenvectors and Eigenvalues**
Matrix decomposition is breaking up a matrix into it's basic components.
If we have a sqare matrix $A$, it has the following eigenvalue equation:

$Av=λv$

If $A$ is the original matrix, it is composed of eigenvector $v$ and eigenvalue $λ$. There is one eigenvector and eigenvalue for each dimension of the parent matrix and not all matrices can be decomposed into eigenvectors and eigenvalues.

In [7]:
from numpy import array,diag 
from numpy.linalg import eig,inv 

A = array([
           [1,2],
           [4,5]
           ])
eigenvals, eigenvecs = eig(A)
print("Eigenvalues:")
print(eigenvals)
print("Eigenvectors:")
print(eigenvecs)

Eigenvalues:
[-0.46410162  6.46410162]
Eigenvectors:
[[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]


Now we can rebuild the matrix from the eigenvalues and eigenvectors:

In [8]:
Q = eigenvecs 
R = inv(Q)

L = diag(eigenvals)
B = Q @ L @ R 
print(B)

[[1. 2.]
 [4. 5.]]
